export const ordres = {
	'Hyménoptères':"Les Hyménoptères ont 2 paires d'ailes membraneuses qui peuvent être jointes au repos (d'où leur nom, Hyménoptères signifiant \"mariage\" et \"ailes\") et des antennes bien développées\nOn les divise en 2 grands groupes : les Symphytes qui ne présentent pas de rétrécissement à la taille et les Apocrites dont l'étranglement est marqué (\"taille de guêpe\")\nLes Hyménoptères ont un appareil buccal du type \"broyeur-lécheur\" qui leur permet d'absorber des aliments liquides comme le nectar\nCe sont souvent de très bons pollinisateurs qui sont parfois utilisés comme auxiliaires de cultures\nOn compte environ 8 000 espèces en France\nExemples d'Hyménoptères : l'Abeille mellifère, les guêpes, les bourdons, les frelons, les ichneumons.",
	'Lépidoptères':"Les Lépidoptères ou papillons se caractérisent par leurs ailes couvertes de minuscules écailles souvent très colorées.\nOn les divise généralement en deux grands groupes : les papillons dits \"de jour\" ou Rhopalocères aux antennes en massue et les papillons dits \"de nuit\" (même si certains volent le jour) ou Hétérocères. Les dessins sur les ailes sont souvent utilisés pour leur identification.\nIls possèdent pour la plupart une trompe qui leur sert à aspirer le nectar.\nOn compte environ 5 000 espèces en France.",
	'Araneae':"Les araignées ne sont pas des Insectes mais des Arachnides : grand groupe d'Arthropodes où l'on trouve également les scorpions, les opilions, les tiques ou encore les acariens\nLes Arachnides n'ont jamais d'ailes ni d'antennes, ils possèdent des yeux simples, des crochets ou chélicères, 8 pattes (6 pour les insectes) et 2 pédipalpes ou \"pattes-mâchoires\" (petites pattes non motrices sur le devant de l'animal).\nAu sein des Arachnides on trouve l'ordre Araneae appelés communément araignées. Leur corps est composé de 2 parties : le céphalothorax (fusion entre la tête et le thorax) et l'abdomen\nElles ont la capacité de pouvoir produire de la soie grâce à leurs filières situées au bout de l'abdomen. Cette soie peut être utilisée pour se déplacer, construire des pièges, des cocons, etc\nLa grande majorité des araignées possède du venin, utilisé pour tuer leurs proies, les consommer ou encore pour se défendre. L'identification des grandes familles est basée, en partie, sur la forme du corps, le nombre et la position des yeux ou encore la forme des toiles (lorsque l'araignée construit une toile pour capturer ses proies)\nOn peut distinguer assez facilement chez les adultes, le mâle de la femelle grâce à ses 2 \"gants de boxe\", petits organes copulateurs ovoïdes au bout des pédipalpes.",
	'Coléoptères':"Les Coléoptères se caractérisent par leurs ailes antérieures totalement coriaces, appelées élytres, formant une solide carapace qui protégent les ailes postérieures utilisées pour voler (Coléoptères signifiant \"étui\" et \"ailes\").\nIls possèdent des pièces buccales broyeuses qui leur permettent d'exploiter des aliments solides très variés comme le bois, les feuilles, les racines, etc.\nLa forme des antennes est un élément important dans leur identification.\nC'est un très grand groupe d'insectes avec environ 9 600 espèces en France. Ils occupent tous les milieux naturels.\nExemple de Coléoptères : le Hanneton, la Cétoine verte, le Doryphore, la Coccinelle, le Bousier.",
	'Hémiptères':"L'ordre: Hémiptères regroupe les punaises, les cigales, les cicadelles et les pucerons.\nLes punaises ont des ailes antérieures coriaces à la base et membraneuse au bout (il y a toutefois des exceptions).\nElles possèdent un appareil buccal de type \"piqueur-suceur\". Si beaucoup sont végétariennes, certaines espèces sont prédatrices.\nLa classification:{ des punaises s'éffectue en partie en fonction du nombre d'articles qui composent les antennes.\nOn compte environ 2 000 espèces en France.\nExemple d'Hétéroptères : la Punaise verte, le Gendarme.",
	'Diptères':"Les Diptères ont, comme leur nom l'indique, 2 ailes. Les ailes antérieures membraneuses sont bien visibles alors que les ailes postérieures sont réduites en \"balanciers\", aussi appelés \"haltères\", utiles dans le vol.\nOn sépare les Diptères en 2 grands groupes : les Nématocères aux antennes composées de nombreux articles et au corps svelte (les moustiques et les tipules) et les Brachycères aux antennes très courtes et au corps trapu (les mouches).\nOn compte environ 8 000 espèces en France.\nExemple de Diptères : les mouches, les moustiques, les taons.",
	'Neuroptères':"Les Neuroptères sont des Insectes au vol lent, aux antennes assez longues parfois terminées en massue et aux ailes disposées, au repos, en toit au dessus du corps.\nOn retrouve dans ce groupe : les Chrysopes, les Fourmilions et les Ascalaphes.\nOn compte 143 espèces en France.",
	'Orthoptères':"Orthoptères est un ordre important d'insectes dans lequel on retrouve les criquets, les sauterelles, les grillons et les courtillières.\nIls possèdent des pattes postérieures sauteuses très développées.",
	'Rhaphidioptères':"Insectes diurnes au corps luisant chassant les pucerons et chenilles. Le thorax allongé forme un long \"cou\".\nOn compte 14 espèces en France.",
	'Collembola':"Ils ont longtemps été considérés comme des insectes primitifs; ils sont aptères et amétaboles (c’est-à-dire dépourvus d'ailes et ne passant pas par une phase larvaire). On tend à les rapprocher aujourd'hui des crustacés4: beaucoup d'espèces ressemblent à de petites crevettes et certains crustacés, comme les talitres, sont également \"sauteurs\"",
};
